// <auto-generated />
using System;
using ClinicWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicWeb.Migrations
{
    [DbContext(typeof(ClinicDbContext))]
    [Migration("20260506234202_AddedConvertingStatusToString")]
    partial class AddedConvertingStatusToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicWeb.Models.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentCategoryId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("ClinicWeb.Models.Entities.AppointmentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DefaultDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppointmentCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Consultation"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Follow-up"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Emergency"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Routine Check-up"
                        });
                });

            modelBuilder.Entity("ClinicWeb.Models.Entities.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 Health Ave, Oslo",
                            Name = "MediConnect Central Clinic",
                            PhoneNumber = "+47 22 33 44 55"
                        },
                        new
                        {
                            Id = 2,
                            Address = "89 Nordic St, Bergen",
                            Name = "MediConnect North Branch",
                            PhoneNumber = "+47 55 66 77 88"
                        },
                        new
                        {
                            Id = 3,
                            Address = "34 Fjord Rd, Stavanger",
                            Name = "MediConnect South Branch",
                            PhoneNumber = "+47 51 22 33 44"
                        });
                });

            modelBuilder.Entity("ClinicWeb.Models.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("SpecialityId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicId = 1,
                            FirstName = "Anna",
                            LastName = "Larsen",
                            SpecialityId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClinicId = 1,
                            FirstName = "Erik",
                            LastName = "Hansen",
                            SpecialityId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClinicId = 1,
                            FirstName = "Sofia",
                            LastName = "Berg",
                            SpecialityId = 3
                        },
                        new
                        {
                            Id = 4,
                            ClinicId = 2,
                            FirstName = "Jonas",
                            LastName = "Nilsen",
                            SpecialityId = 4
                        },
                        new
                        {
                            Id = 5,
                            ClinicId = 2,
                            FirstName = "Maria",
                            LastName = "Andersen",
                            SpecialityId = 5
                        },
                        new
                        {
                            Id = 6,
                            ClinicId = 2,
                            FirstName = "Tobias",
                            LastName = "Dahl",
                            SpecialityId = 6
                        },
                        new
                        {
                            Id = 7,
                            ClinicId = 3,
                            FirstName = "Ingrid",
                            LastName = "Svensson",
                            SpecialityId = 7
                        },
                        new
                        {
                            Id = 8,
                            ClinicId = 3,
                            FirstName = "Marcus",
                            LastName = "Johansen",
                            SpecialityId = 2
                        },
                        new
                        {
                            Id = 9,
                            ClinicId = 3,
                            FirstName = "Astrid",
                            LastName = "Olsen",
                            SpecialityId = 1
                        });
                });

            modelBuilder.Entity("ClinicWeb.Models.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverLicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalInsuranceMemberId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialSecurityNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ClinicWeb.Models.Entities.Speciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specialities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "General Practice"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cardiology"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Orthopedics"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pediatrics"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Neurology"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Psychiatry"
                        });
                });

            modelBuilder.Entity("ClinicWeb.Models.Entities.Appointment", b =>
                {
                    b.HasOne("ClinicWeb.Models.Entities.AppointmentCategory", "Category")
                        .WithMany("Appointments")
                        .HasForeignKey("AppointmentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicWeb.Models.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicWeb.Models.Entities.Patient", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Doctor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClinicWeb.Models.Entities.Doctor", b =>
                {
                    b.HasOne("ClinicWeb.Models.Entities.Clinic", "Clinic")
                        .WithMany("Doctors")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicWeb.Models.Entities.Speciality", "Speciality")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("ClinicWeb.Models.Entities.AppointmentCategory", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ClinicWeb.Models.Entities.Clinic", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("ClinicWeb.Models.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ClinicWeb.Models.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ClinicWeb.Models.Entities.Speciality", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
